---
- hosts: all
  become: true
  tasks:
    - name: Install Tools
      yum: name={{ item }} state=latest
      with_items:
        - git
        - vim
    - name: Add target1 to hosts
      lineinfile:
        path: /etc/hosts
        regexp: '10.0.0.1 target1'
        line: '10.0.0.1 target1'
