---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Install Tools
      yum: name={{ item }} state=latest
      with_items:
        - git
        - vim
    - name: Add target1 to hosts
      lineinfile:
        path: /etc/hosts
        regexp: '10.0.0.1 target1'
        line: '10.0.0.1 target1'
    - name: Install .gitconfig
      get_url:
        url: https://raw.githubusercontent.com/bbkane/backup/master/common/.gitconfig
        dest: /home/vagrant/.gitconfig
